knp_gaufrette:
    stream_wrapper: ~

    adapters:
        profile_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/profile"
        plant_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/plants"
        UserPlantPic_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/UserPlants"

    filesystems:
        profilePic_fs:
            adapter: profile_adapter
        plantPic_fs:
            adapter: plant_adapter
        userPlantPic_fs:
            adapter: UserPlantPic_adapter

vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type: attribute

    mappings:
        profile:
            uri_prefix: /images/profile
            upload_destination: profilePic_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        plants:
            uri_prefix: /images/plants
            upload_destination: plantPic_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        UserPlants:
            uri_prefix: /images/UserPlants
            upload_destination: '%kernel.project_dir%/public/images/UserPlants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

when@test:
    knp_gaufrette:
        adapters:
            product_adapter:
                local:
                    directory: "%kernel.cache_dirname%/images"



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
