controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

plant_search:
    path: /plants/search
    controller: App\Controller\PlantsController::search
    methods: [GET]